# Generated by Django 5.0.7 on 2024-08-11 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_userresponse'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserResponse',
        ),
    ]
